// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/tools/jwt/app/kubernetes.go

// Package mock_app is a generated GoMock package.
package mock_app

import (
	gomock "github.com/golang/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
	reflect "reflect"
)

// Mockk8sClientFactory is a mock of k8sClientFactory interface
type Mockk8sClientFactory struct {
	ctrl     *gomock.Controller
	recorder *Mockk8sClientFactoryMockRecorder
}

// Mockk8sClientFactoryMockRecorder is the mock recorder for Mockk8sClientFactory
type Mockk8sClientFactoryMockRecorder struct {
	mock *Mockk8sClientFactory
}

// NewMockk8sClientFactory creates a new mock instance
func NewMockk8sClientFactory(ctrl *gomock.Controller) *Mockk8sClientFactory {
	mock := &Mockk8sClientFactory{ctrl: ctrl}
	mock.recorder = &Mockk8sClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockk8sClientFactory) EXPECT() *Mockk8sClientFactoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *Mockk8sClientFactory) Get() (kubernetes.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(kubernetes.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *Mockk8sClientFactoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockk8sClientFactory)(nil).Get))
}
