apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - native-pipeline.yaml
  - secure-image-pipeline.yaml
  - kse-pipeline.yaml
  - secure-image-kse-pipeline.yaml
